import chaotic_behavior_solutions_dynamical_problems_lemma_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace chaotic_behavior_solutions_dynamical_problems_lemma_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end chaotic_behavior_solutions_dynamical_problems_lemma_canonical_lane_mathlib
end HautevilleHouse
